### ISSUE TITLE
Using Bootstrap to create a template

### ISSUE THREAD

**Issue by thealphadollar** [GirlScriptSummerOfCode/GirlScript_India#1]
GirlScript website is to be made gathering inspiration from [Django Girls](https://djangogirls.org/). It is required to create a template for the same. We can use the [Starter Template](https://getbootstrap.com/docs/4.1/examples/starter-template/) for the same, and students can also recommend if they find a better template for the same.

Later we should be embedding this into Django Code.

The issue will be followed by finalizing the design which will include adding logos and much more.

**Comment by mayankk98** [comment]
I would like to take this up

**Comment by MadhavBahl** [comment]
I have a great starter template, if you assign me to this :)

**Comment by thealphadollar** [comment]
Hey @MadhavBahlMD , thanks for the interest. But since we are to assign issues by the time of claim, **this is assigned to @mayankk98** As is the method of opensource, it would be amazing if @MadhavBahlMD you could support @mayankk98  on the issue.

Note: Points will be given to the assigned person only.

**Comment by codestryker** [comment]
I recently done google scholarship program so i can able to done it.

**Comment by MadhavBahl** [comment]
Yeah sure, looks good :)

@mayankk98 do contact me if you need help.

**Comment by mayankk98** [comment]
I would like to see the template you have in mind, you can email it to mayankkhandelwal92@gmail.com if you want

**Comment by MadhavBahl** [comment]
Here you go @mayankk98 ,
https://freehtml5.co/ This is the website which has some awesome templates,

https://freehtml5.co/host-free-html5-bootstrap-4-template-for-web-hoster/ this one seems quite fit for purpose

**Comment by Anujg935** [comment]
I have made 1 template so can you assign this issue to me.

**Comment by mayankk98** [comment]
I wanted to know what sections are required for the girlscript site. Whether you want a single page website or multi-page. I also wanted access to the event pictures, logos and content for the site.

**Comment by thealphadollar** [comment]
As I already mentioned, the website needs to be inspired by https://djangogirls.org/ 
Along with that, [here](https://docs.google.com/document/d/1cYxBlEb_CpxmvYZOsjZbp5OnBUZeXA7WKSrweMFFyo4/edit?usp=sharing) is a very rough document that lists the requirements. The document will be refined soon.

**Comment by Anujg935** [comment]
i made a template please have a look at it

**Comment by mayankk98** [comment]
This issue was assigned to me :(

**Comment by thealphadollar** [comment]
This issue has already been assigned.

**Comment by Anujg935** [comment]
ok sorry
But making the whole template is itself a big project so the mentors should divide the whole issue to some participants

**Comment by thealphadollar** [comment]
@mayankk98  Can you make me aware of whatever progress you've made?

**Comment by mayankk98** [comment]
I have started working on it.  As of now I'm making separate pages and trying out suitable font, color schemes and using lorem ipsum as dummy content. I'll start working on the landing page soon. I really need the logos, introduction video and images though

**Comment by thealphadollar** [comment]
Do not worry about colour schemes and logo, please leave space for them. We
will incorporate them later and modify design. Keep me informed, and great
going :D

**Comment by mayankk98** [comment]
The issue I'm assigned to is to create a bootstrap template but I don't know if I'll be able to complete it before the first evaluation and I want to continue to complete that issue post the 1st evaluation date too. Is that possible ?

**Comment by thealphadollar** [comment]
Please report to us (using issue comment) with the progress and we'll see
if it's possible. :D

**Comment by mayankk98** [comment]
I have completed the upcoming events, contact us/ social media and sponsors section. I don't have the introduction video, get inspired blog section material and all that. Also I'm facing issue with the functionality of the map and it's chapters being displayed, that's why it's taking time

**Comment by vishwarajanand** [comment]
You may skip some of the side features like map markers functionality, etc. Just try to complete the skeleton of the website. You can keep improving on the code later @mayankk98

**Comment by thealphadollar** [comment]
@mayankk98 Seeing the amount of work being put, efforts required and your love towards this, I'm increasing the issue level to "topcoder".

**Comment by vaarigupta** [comment]
Is this issue still avaialble to work ?

**Comment by mayankk98** [comment]
You can give me feedback, I'll be making the changes

**Comment by vishwarajanand** [comment]
Participants, please update your progress with this task.

**Comment by mayankk98** [comment]
I had already made a pull requests and I'm making more improvements and will make more pull requests in some days

**Comment by thealphadollar** [comment]
Done for now.

We are continuing with the integration phase and anyone willing to work on this issue can do it for contribution and we will integrate his code if it's good enough in the improvement phase.

**Comment by vishwarajanand** [comment]
Closing this issue, since the event is closed.
