### ISSUE TITLE
Integrate Github into out Slack channel

### ISSUE THREAD

**Issue by thealphadollar** [GirlScriptSummerOfCode/GirlScript_India#2]
This is an easy issue. There are already many tools (one is [this](https://github.com/integrations/slack)) that exist and, if you wish you can create one yourself, not recommended though.

Use (or create) any tool you wish, it should notify of the following at least:
- Opening of issue (with labels)
- Assignment of issue
- Closing of issue

NOTE: In GitHub API, PRs are same as issues and hence this is applicable to PRs too.

**Comment by MadhavBahl** [comment]
I would like to do this one :)

**Comment by codestryker** [comment]
I can do this .

**Comment by thealphadollar** [comment]
**Assigned to @MadhavBahlMD**

I found out we already have such an app installed: all you need to do is connect it to this repository, shouldn't take much time.

**Comment by MadhavBahl** [comment]
Alright, will do it as soon as I get time :)

Thanks for assigning me :D

**Comment by codestryker** [comment]
Sir,i added the github to the slack.

**Comment by thealphadollar** [comment]
@samyak8853 The issue isn't solved yet. Please do not take over issues assigned to other users, though I like your enthusiasm :grinning:

**Comment by MadhavBahl** [comment]
@thealphadollar this is done :smile: 

This issue can be closed now.

**Comment by thealphadollar** [comment]
+10 to @MadhavBahlMD

**Comment by MadhavBahl** [comment]
Thanks @thealphadollar  :smiley:
