### ISSUE TITLE
Create HTML/JS website to accept paypal/stripe/patreon donations

### ISSUE THREAD

**Issue by vishwarajanand** [GirlScriptSummerOfCode/GirlScript_India#6]
**Deliverables:**
1. A website in HTML/JS which enables users to donate to a given account in Paypal, Stripe and Patreon. For now, you can use your own custom account to demo that the website is functional.
2. Please keep the demo configurable, so that the same module can be reused later with minimal changes to support GirlScript donations.
3. Make a folder demos/donations/[your-name]/[all-your-codefiles-goes-here-****].

**Evaluation criteria:**
1. Grade A: Neatly done, can be integrated easily.
2. Grade B: The task is completed, but integration needs some changes.
3. Grade C: The task is completed, but we may need to improve.

When you submit the PR, please provide screenshots to show that the PR actually works.

**Comment by devesh-verma** [comment]
I want to work on this

**Comment by vishwarajanand** [comment]
@devshiva619 Go ahead!
Other participants, you can also submit MR to this issue till it is open. Please note that we welcome multiple submissions from different participants. We would evaluate your PRs accordingly. The best fit for our use-case shall be taken forward for integration to final website.

Alternatively, if you feel that the issue is too big and you want to collaborate with your group to do so. Please create a repository of your own and once completed, share your repo's link here. All contributions are welcome!

**Comment by devesh-verma** [comment]
What about the points, are all people getting points, like which all will be Good ones?

**Comment by vishwarajanand** [comment]
Everyone who submits PRs would be granted some points and depending on total aggregated points, I think there are some rewards to be given at the end.

As a mentor, it's much more manageable to give grades as of now. Don't worry about the scoring of grades, we would keep participants updated eitherways.

**Comment by sourabhpruthi10** [comment]
@thealphadollar I also would like to work on this issue

**Comment by Pallavi024** [comment]
I would also like to work on this issue @vishwarajanand and how to get myself assigned ?

**Comment by megha070** [comment]
I would like to work on this sir !

**Comment by iriyagupta** [comment]
We have to submit the PRs till 6 or before 6 ? @vishwarajanand

**Comment by vishwarajanand** [comment]
Issues would be open till the end of the program, so that the avenues to learn even for beginners are always open.

**Comment by codestryker** [comment]
I will also work on this

**Comment by codestryker** [comment]
Sir,what type of website we are creating and what will be its functionality

**Comment by vishwarajanand** [comment]
You can consider [https://djangogirls.org/](https://djangogirls.org/) as a template. But we would have several modifications/chanegs on the go.

**Comment by devesh-verma** [comment]
@vishwarajanand hey in this you want us to make just a static website for the issue for you want a functional website which can accept payments

**Comment by vishwarajanand** [comment]
Any website would work, even a static website.

Just follow two points: 
1. Avoid overcomplicating things, keep the code minimal. 
2. Keep the code configurable so that the payments can be later pointed to GirlScript's donations account.

**Comment by devshiva619** [comment]
@vishwarajanand I think I wasn't clear in my last comment. I was asking if we need to implement the payment process or you need just a static website. 
Means the payment process is to be done or it will be done by girlscript

**Comment by vishwarajanand** [comment]
You do not need to implement the donation payment process by yourself. For example, Once you have a Paypal account ready, you can use the account to get a donate button code which can be embedded in a HTML. For reference, check this: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/

**Comment by devesh-verma** [comment]
@vishwarajanand thanks a lot for telling me this, I was implementing stripe payment with nodejs 😄

**Comment by vishwarajanand** [comment]
Good that we discussed it, in general before starting to implement a solution it's better to discuss the different ways a task can be done and how you are thinking to do it. This avoids over-work and sometimes brings up a very simple solution to complicated problems.

In Agile world, people brainstorm ideas before implementation and in waterfall development practices, people tend to write developer design documents.

**Comment by devshiva619** [comment]
@vishwarajanand hey I wanted some content related to Girlscript to use it in the website. I was trying to load the girlscript website but looks like it isnt working.

**Comment by mayankk98** [comment]
the participants working on other issues also need content

**Comment by thealphadollar** [comment]
I've forwarded the link to document containing some content in the
girlsscript channel.

**Comment by vishwarajanand** [comment]
Participants, please update your progress with this task.

**Comment by thealphadollar** [comment]
Done in #9 

We are continuing with  the integration phase and anyone willing to work on this issue can do it for contribution and we will integrate his code if it's good enough in the improvement phase.

**Comment by vishwarajanand** [comment]
Closing this issue, since the event is closed.
